#!/bin/bash

#scp -r . aduquette@aduquette.humanoriented.com:/home/aduquette/aduquette.humanoriented.com/public 2> /dev/null

rsync -aP --exclude '.git' ./ aduquette@aduquette.humanoriented.com:/home/aduquette/aduquette.humanoriented.com/public
